### ISSUE TITLE
Tweet obselete 

### ISSUE THREAD

**Issue by mrhouzlane** [EkuboProtocol/.github#3]
## Description : 

Obslete implementation of Twitter (X now) 

## Implementation 
In : https://app.ekubo.org/leaderboard, when clicking on Tweet (first of all it should be X) : 

This is the message generated : I climbed to position #1 on the @EkuboProtocol leaderboard with 0 points! https://app.ekubo.org/leaderboard 

I only made 1 transaction on Ekubo, so the position should not be #1.

**Comment by moodysalem** [comment]
fixed now
